name:                telegram-vk-bot
version:             0.1.0.0
github:              "githubuser/telegram-vk-bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/telegram-vk-bot#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- http-client
- http-conduit
- aeson
- hspec
- configurator
- mtl
- containers

library:
  source-dirs: src

executables:
  telegram-vk-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telegram-vk-bot

tests:
  telegram-vk-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telegram-vk-bot
